---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: traefik-acme
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Mi
  hostPath:
    path: /mnt/k8s_storage/traefik-acme-pvc
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-acme
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: traefik-acme
