global:
    resolve_timeout: 5m
receivers:
-   name: "null"
-   name: healthchecksio
    webhook_configs:
    -   url: ENC[AES256_GCM,data:GmF++32cX3OTy80FcuHZWwbhfE60kd0l7NlI9SUjBJYnhz7fFCvapf37oBAfFrDfI1P0Y9Bk048=,iv:w3fJ24OLMtHUhY4DxsnLGRy+99ij4c6lOFqlqR5d744=,tag:5XXgg/VvJcrHzLFPQp0m8A==,type:str]
-   name: thepit
    opsgenie_configs:
    -   api_key: ENC[AES256_GCM,data:ViaoktmCAhcrlDJIOBcAxY38iVSQICgiGo97wlb6gFPMJHY/,iv:1/Q9f4sIRHBNiBxNfiDQptreDKtfCy4Ylph53JpCN68=,tag:WZ5pcBtfYF/rk5CHKt7nwg==,type:str]
route:
    group_interval: 5m
    group_wait: 30s
    receiver: thepit
    repeat_interval: 12h
    group_by:
    - job
    routes:
    -   match:
            alertname: Watchdog
        repeat_interval: 30m
        receiver: healthchecksio
sops:
    kms:
    -   arn: arn:aws:kms:us-west-2:535773024242:key/b2fc2ade-40d5-46cf-ba1b-d183ec4c7930
        created_at: '2020-05-01T03:36:28Z'
        enc: AQICAHgCSSD7irD6sDR4tuQvDixl4G5KXCqyEJEynNJVZ6u0egF81n5LShyOZY+JOs+DOaLoAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMXljiYN1CtkxDJp6XAgEQgDt5DxzLKzHcyr7y2YJ45dSb+4szWJKhT0HvKUIkaL7nJu1mPLPM5fbOuu/LuhIv069/xOU9kStlB/RzHw==
        aws_profile: ""
    -   arn: arn:aws:kms:us-east-1:535773024242:key/39457849-4295-4ae8-8ded-5e089b06395d
        created_at: '2020-05-01T03:36:28Z'
        enc: AQICAHjQsiM5Q10UVnP1cLv8ygIpFSMgT1YPclgMVueLWHCfPAFTJK0cHTrtFJac1imu3OO3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPeZaelKxGCB8FpWLAgEQgDskbBMWEyPadPeebYvIP8DkpQ+GmzWqWTb0uDlJv32g8cn9qQNnXy9LLCDKvU3mQx5ovdiA6Fm1UH5zTw==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-05-01T04:30:07Z'
    mac: ENC[AES256_GCM,data:vrm6oApjAGkmR3pzlc3fnfpZek/cCKWPt8Yh/YgHz0PCdToswcFRNCUigPDhOnjKKfJuUR2JJWDl602HHdKQ5EWOitiW1AimJ0Zkc+tORWZPUtPzToEKRTAol9coCmu+d4rHlqGLAil3l5zebS5NZZNg4M7xsxPgJFXy03H52Sc=,iv:TA1Yasht4dX4IgjDJdoqFYbVGIjftS5sVZA8ymNDqwA=,tag:U5/fd0APXUXf8vOq95QXuw==,type:str]
    pgp: []
    encrypted_regex: ^.*_configs$
    version: 3.5.0
