apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:unifi:privileged
  namespace: unifi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:unifi
