apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: thepit
spec:
  releaseName: calibre-web
  targetNamespace: thepit
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    git: https://github.com/ericbisme/cailbre-web.git
    ref: master
    path: /
  values:
    volumes:
    - name: calibre
      persistentVolumeClaim:
        claimName: media
    - name: calibre-web
      persistentVolumeClaim:
        claimName: calibre-web

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: books.ericbisme.net
          paths: 
            - "/"

    persistence:
      data:
        claimName: "books"
      config:
        claimName: "calibre-config"

    resources:
      limits:
        cpu: 150m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
