---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: thepit
  helm.fluxcd.io/automated: "true"
spec:
  releaseName: calibre-web
  targetNamespace: thepit
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: calibre-web
    version: 4.3.1
  values:
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: calibre-config
      books:
        enabled: true
        mountPath: /books
        existingClaim: books

    env:
      PUID: 1000
      PGID: 1000

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: books.ericbisme.net
          paths: 
            - path: "/"
              pathType: Prefix

    podSecurityContext:
       fsGroup: 1000
