---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: thepit
  helm.fluxcd.io/automated: "true"
spec:
  releaseName: calibre-web
  targetNamespace: thepit
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    git: https://k8s-at-home.com/charts/
    name: calibre-web
    version: 4.3.1
  values:
    persistence:
      config:
        enabled: true
        existingClaim: calibre-config
      books:
        enabled: true
        existingClaim: books

    env:
    - name: PUID
      value: 1000
    - name: PGID
      value: 1000

    common:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: books.ericbisme.net
            paths:
              - "/"

      podSecurityContext:
         fsGroup: 1000

      securityContext:
         capabilities:
           drop:
           - ALL
         readOnlyRootFilesystem: true
         runAsNonRoot: true
         runAsUser: 1000
