apiVersion: v1
kind: Endpoints
metadata:
  name: cluster-external-node-exporter
  labels:
    k8s-app: cluster-external-node-exporter
    jobLabel: cluster-external-node-exporter
subsets:
  - addresses:
    - ip: 192.168.10.125
    ports:
      - name: http-metrics
        port: 9100
        protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: cluster-external-node-exporter
    jobLabel: cluster-external-node-exporter
  name: cluster-external-node-exporter
  namespace: klippy
spec:
  type: ExternalName
  externalName: cluster-external-node-exporter.ericbisme.net
  ports:
  - name: node-exporter
    port: 9100
    protocol: TCP
    targetPort: 9100

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    k8s-app: cluster-external-node-exporter
    release: prometheus-operator
    jobLabel: cluster-external-node-exporter
  name: cluster-external-node-exporter
  namespace: klippy
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    port: http-metrics
    targetPort: 9100
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - klippy
  selector:
    matchLabels:
      k8s-app: cluster-external-node-exporter

