apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-operator
  labels:
    app: helm-operator
    chart: helm-operator-0.3.0
    release: helm-operator
    heritage: Helm
  namespace: flux
---
apiVersion: v1
kind: Secret
metadata:
  name: flux-helm-repositories
  namespace: flux
type: Opaque
data:
  repositories.yaml: YXBpVmVyc2lvbjogdjEKZ2VuZXJhdGVkOiAwMDAxLTAxLTAxVDAwOjAwOjAwWgpyZXBvc2l0b3JpZXM6Ci0gbmFtZTogc3RhYmxlCiAgdXJsOiBodHRwczovL2t1YmVybmV0ZXMtY2hhcnRzLnN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20KICBjYWNoZTogL3Zhci9mbHV4ZC9oZWxtL3JlcG9zaXRvcnkvY2FjaGUvc3RhYmxlLWluZGV4LnlhbWwKICBjYUZpbGU6ICIiCiAgY2VydEZpbGU6ICIiCiAga2V5RmlsZTogIiIKICBwYXNzd29yZDogIiIKICB1c2VybmFtZTogIiIKLSBuYW1lOiBmbHV4Y2QKICB1cmw6IGh0dHBzOi8vY2hhcnRzLmZsdXhjZC5pbwogIGNhY2hlOiAvdmFyL2ZsdXhkL2hlbG0vcmVwb3NpdG9yeS9jYWNoZS9mbHV4Y2QtaW5kZXgueWFtbAogIGNhRmlsZTogIiIKICBjZXJ0RmlsZTogIiIKICBrZXlGaWxlOiAiIgogIHBhc3N3b3JkOiAiIgogIHVzZXJuYW1lOiAiIgotIG5hbWU6IHBvZGluZm8KICB1cmw6IGh0dHBzOi8vc3RlZmFucHJvZGFuLmdpdGh1Yi5pby9wb2RpbmZvCiAgY2FjaGU6IC92YXIvZmx1eGQvaGVsbS9yZXBvc2l0b3J5L2NhY2hlL3BvZGluZm8taW5kZXgueWFtbAogIGNhRmlsZTogIiIKICBjZXJ0RmlsZTogIiIKICBrZXlGaWxlOiAiIgogIHBhc3N3b3JkOiAiIgogIHVzZXJuYW1lOiAiIg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-operator-kube-config
  namespace: flux
data:
  config: |
    apiVersion: v1
    clusters: []
    contexts:
    - context:
        cluster: ""
        namespace: default
        user: ""
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users: []
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: helm-operator
  labels:
    app: helm-operator
    chart: helm-operator-0.3.0
    release: helm-operator
    heritage: Helm
  namespace: flux
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: helm-operator
  labels:
    app: helm-operator
    chart: helm-operator-0.3.0
    release: helm-operator
    heritage: Helm
  namespace: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-operator
subjects:
- name: helm-operator
  namespace: flux
  kind: ServiceAccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-operator
  labels:
    app: helm-operator
    chart: helm-operator-0.3.0
    release: helm-operator
    heritage: Helm
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-operator
      release: helm-operator
  template:
    metadata:
      annotations:
        checksum/repositories: 5ec1dbb4e14760710846f3e433ac4ce462f6da2f86bcd904544b768d42ea1730
        fluxcd.io/automated: '"true"'
        fluxcd.io/tag.flux-helm-operator: 1.0.*
        linkerd.io/inject: enabled
      labels:
        app: helm-operator
        release: helm-operator
    spec:
      serviceAccountName: helm-operator
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 256
      - name: repositories-yaml
        secret:
          secretName: flux-helm-repositories
      - name: repositories-cache
        emptyDir: {}
      containers:
      - name: flux-helm-operator
        image: docker.io/fluxcd/helm-operator:1.0.0-rc4
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3030
        livenessProbe:
          httpGet:
            port: 3030
            path: /healthz
          initialDelaySeconds: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 3030
            path: /healthz
          initialDelaySeconds: 1
          timeoutSeconds: 5
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true
        - name: repositories-yaml
          mountPath: /var/fluxd/helm/repository/repositories.yaml
          subPath: repositories.yaml
          readOnly: true
        - name: repositories-cache
          mountPath: /var/fluxd/helm/repository/cache
        args:
        - --log-format=fmt
        - --git-timeout=20s
        - --git-poll-interval=5m
        - --charts-sync-interval=3m
        - --update-chart-deps=true
        - --log-release-diffs=false
        - --workers=2
        - --tiller-namespace=kube-system
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
