apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: klippy
  helm.fluxcd.io/automated: "true"
spec:
  releaseName: kube-prometheus-stack
  targetNamespace: klippy
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 12.12.1
  values:
    prometheusOperator:
      createCustomResource: false
      cleanupCustomResource: false
    alertmanager:
      alertmanagerSpec:
        useExistingSecret: true
        configSecret: alertmanager-config
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          kubernetes.io/tls-acme: "true"
        paths:
          - /
        hosts:
           - alertmanager.ericbisme.net
        labels: {}
        tls: []
    
    kubelet:
      resource: false

    ## Using default values from https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
    ##
    grafana:
      enabled: true

      ## Deploy default dashboards.
      ##
      defaultDashboardsEnabled: true

      adminPassword: prom-operator

      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          kubernetes.io/tls-acme: "true"
        paths:
          - /
        hosts:
           - grafana.ericbisme.net
        labels: {}
        tls: []

      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          provider:
            foldersFromFilesStructure: true
          annotations: 
            k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"

        datasources:
          enabled: true
          defaultDatasourceEnabled: true
          ## Create datasource for each Pod of Prometheus StatefulSet;
          ## this uses headless service `prometheus-operated` which is
          ## created by Prometheus Operator
          ## ref: https://git.io/fjaBS
          createPrometheusReplicasDatasources: false
          label: grafana_datasource

    ## Deploy a Prometheus instance
    ##
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          kubernetes.io/tls-acme: "true"
        paths:
          - /
        hosts:
           - prometheus.ericbisme.net
        labels: {}
        tls: []
      prometheusSpec:
        retention: 90d
        retentionSize: "50GB"
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: managed-nfs-storage
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
