---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: klippy
  helm.fluxcd.io/automated: "true"
spec:
  releaseName: loki
  targetNamespace: klippy
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://grafana.github.io/helm-charts
    name: loki
    version: 2.3.0
  values:
    persistence:
      enabled: true
      accessModes:
      - ReadWriteOnce
      size: 10Gi
      annotations: {}

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: promtail
  namespace: klippy
  helm.fluxcd.io/automated: "true"
spec:
  releaseName: promtail
  targetNamespace: klippy
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://grafana.github.io/helm-charts
    name: promtail
    version: 3.0.0
