apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  releaseName: metallb
  targetNamespace: kube-system
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.12.0
  values:
    configInline:
      address-pools:
        - name: default
          protocol: bgp
          addresses:
          - 192.168.10.128-192.168.10.254
          avoid-buggy-ips: true
      peers:
        - peer-address: 192.168.10.1
          peer-asn: 64501
          my-asn: 64500
    controller:
      resources:
        requests:
          cpu: 50m
          memory: 4Mi
        limits:
          cpu: 150m
          memory: 16Mi
    speaker:
      resources:
        requests:
          cpu: 50m
          memory: 8Mi
        limits:
          cpu: 250m
          memory: 20Mi
