---
# https://community.ui.com/questions/BGP-instructions-for-USG-K8s-MetalLB/b61e2f67-34f2-4571-9140-8d6b9cde2d72
# http://blog.cowger.us/2019/02/10/using-metallb-with-the-unifi-usg-for-in-home-kubernetes-loadbalancer-services.html
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  releaseName: metallb
  targetNamespace: kube-system
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: metallb
    version: 2.0.4
  values:
    configInline:
      address-pools:
        - name: default
          protocol: bgp
          addresses:
          - 192.168.10.128-192.168.10.254
          avoid-buggy-ips: true
        - name: unifi
          protocol: bgp
          addresses:
          - 192.168.1.3
          avoid-buggy-ips: true
      peers:
        - peer-address: 192.168.10.1
          peer-asn: 64501
          my-asn: 64500
        - peer-address: 192.168.1.1
          peer-asn: 64503
          my-asn: 64502
    controller:
      resources:
        requests:
          cpu: 50m
          memory: 4Mi
        limits:
          cpu: 256m
          memory: 32Mi
    speaker:
      resources:
        requests:
          cpu: 50m
          memory: 8Mi
        limits:
          cpu: 300m
          memory: 48Mi
