apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
  helm.fluxcd.io/automated: "true"
spec:
  releaseName: metrics-server
  targetNamespace: kube-system
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 2.11.1
  values:
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
