---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: thepit
  helm.fluxcd.io/automated: "true"
spec:
  releaseName: plex
  targetNamespace: thepit
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: plex
    version: 2.1.1
  values:
    allowedNetworks:
      - 127.0.0.1
      - 10.233.0.0/16
      - 192.168.10.0/24
      - 192.168.1.0/24

    changeConfigDirOwnership: "false"
    plexUid: 1000
    plexGid: 1000
    advertiseIp: "https://192.168.10.132:443"

    # Set the timezone of the plex server
    timezone: America/Denver

    serviceTCP:
      type: LoadBalancer
      loadBalancerIP: 192.168.10.132
      annotations:
        metallb.universe.tf/allow-shared-ip: plex-svc
      port: 32400

    serviceUDP:
      type: LoadBalancer
      loadBalancerIP: 192.168.10.132
      annotations:
        metallb.universe.tf/allow-shared-ip: plex-svc

    persistence:
      transcode:
        enabled: false
      data:
        claimName: "media"
      config:
        claimName: "plex-config"

    podAnnotations:
      linkerd.io/inject: enabled

    # Probes configuration
    probes:
      liveness:
        initialDelaySeconds: 120
        failureThreshold: 5
        timeoutSeconds: 5
      readiness:
        initialDelaySeconds: 120
        failureThreshold: 5
        timeoutSeconds: 5

    resources:
      limits:
        cpu: 4
        memory: 16Gi
      requests:
        cpu: 250m
        memory: 500Mi

    certificate:
      pkcsMangler:
        enabled: true
        certificateSecret:
          name: "plex-ericbisme-net"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-ericbisme-net
  namespace: thepit
spec:
  secretName: plex-ericbisme-net
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - ericbisme.net
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - plex.ericbisme.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io

