apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: thepit
  helm.fluxcd.io/automated: "true"
spec:
  releaseName: plex
  targetNamespace: thepit
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://billimek.com/billimek-charts/ 
    name: plex
    version: 1.2.0
  values:
    image:
      tag: plexpass
      pullPolicy: IfNotPresent

    # claimToken: ""

    changeConfigDirOwnership: "false"
    plexUid: 1000
    plexGid: 1000
    advertiseIp: "https://192.168.10.128:443"

    # Set the timezone of the plex server
    timezone: America/Denver

    service:
      type: ClusterIP
      port: 32400

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
      hosts:
       - plex.ericbisme.net

    rbac:
      create: true
      # Specify create: false and serviceAccountName to manually manage the service
      # account for this deployment
      ## serviceAccountName: ""

    persistence:
      transcode:
        enabled: true
        emptyDir:
          medium: "Memory"
      data:
        claimName: "media"
      config:
        claimName: "plex-config"

    podAnnotations:
      linkerd.io/inject: enabled

    # Probes configuration
    probes:
      liveness:
        initialDelaySeconds: 120
        failureThreshold: 5
        timeoutSeconds: 5
      readiness:
        initialDelaySeconds: 120
        failureThreshold: 5
        timeoutSeconds: 5

    resources:
      limits:
        cpu: 4
        memory: 16Gi
      requests:
        cpu: 250m
        memory: 500Mi
