---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-ericbisme-net
  namespace: thepit
spec:
  secretName: unifi-ericbisme-net
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - ericbisme.net
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - unifi.ericbisme.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io

