---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    helm.fluxcd.io/automated: "true"
    linkerd.io/inject: enabled
  name: unifi-poller
  namespace: klippy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: unifi-poller
  template:
    metadata:
      labels:
        k8s-app: unifi-poller
    spec:
      containers:
      - image: golift/unifi-poller:latest
        name: unifi-poller
        ports:
        - containerPort: 9130
          name: metrics
        volumeMounts:
          - name: config
            mountPath: "/etc/unifi-poller"
        env:
          - name: UP_UNIFI_DEFAULT_URL
            value: "https://192.168.1.2"
          - name: UP_UNIFI_DEFAULT_VERIFY_SSL
            value: "false"
          - name: UP_UNIFI_DEFAULT_SAVE_DPI
            value: "true"
          - name: UP_INFLUXDB_DISABLE
            value: "true"
      volumes:
        - name: config
          secret:
            secretName: unifi-poller-credentials

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: unifi-poller
  name: unifi-poller
  namespace: klippy
spec:
  ports:
  - name: http-metrics
    port: 9130
    protocol: TCP
    targetPort: metrics
  selector:
    k8s-app: unifi-poller

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: unifi-poller
    release: kube-prometheus-stack
  name: unifi-poller
  namespace: klippy
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: unifi-poller
  namespaceSelector:
    matchNames:
    - klippy
  endpoints:
  - interval: 60s
    port: http-metrics
    path: "/metrics"
    targetPort: 9130
