---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi-controller
  namespace: unifi
  helm.fluxcd.io/automated: "true"
spec:
  releaseName: unifi-controller
  targetNamespace: unifi
  timeout: 300
  resetValues: false
  forceUpgrade: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: unifi
    version: 1.3.1
  values:
    guiService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.2
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"
        metallb.universe.tf/address-pool: unifi
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.2
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"
        metallb.universe.tf/address-pool: unifi
    stunService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.2
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"
        metallb.universe.tf/address-pool: unifi
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.2
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"
        metallb.universe.tf/address-pool: unifi
    syslogService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.2
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"
        metallb.universe.tf/address-pool: unifi
    speedtestService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.2
      annotations:
        metallb.universe.tf/allow-shared-ip: "true"
        metallb.universe.tf/address-pool: unifi
    mongodb:
      enabled: false
      dbUri: mongodb://unifi-mongodb/unifi
      statDbUri: mongodb://unifi-mongodb/unifi_stat
      databaseName: unifi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1500Mi
    jvmInitHeapSize: 1024M
    jvmMaxHeapSize: 1024M
    extraVolumes:
      - name: unifi-backup
        persistentVolumeClaim:
          claimName: unifi-backup
    extraVolumeMounts:
      - name: unifi-backup
        mountPath: /var/lib/unifi/backup/autobackup/
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
      path: /
      hosts:
        - unifi.ericbisme.net
