---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    helm.fluxcd.io/automated: "true"
    linkerd.io/inject: enabled
  name: unifi-exporter
  namespace: klippy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: unifi-exporter
  template:
    metadata:
      labels:
        k8s-app: unifi-exporter
    spec:
      containers:
      - image: jessestuart/unifi_exporter:v0.4.0
        name: unifi-exporter
        command:
          - /bin/unifi_exporter
        args:
          - "-config.file=/unifi_exporter/config.yml"
        #        command:
        #          - /bin/sleep
        #        args:
        #          - "10000"
        ports:
        - containerPort: 9130
          name: metrics
        volumeMounts:
          - name: config
            mountPath: "/unifi_exporter"
      volumes:
        - name: config
          secret:
            secretName: unifi-exporter-credentials

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: unifi-exporter
  name: unifi-exporter
  namespace: klippy
spec:
  ports:
  - name: http-metrics
    port: 9130
    protocol: TCP
    targetPort: metrics
  selector:
    k8s-app: unifi-exporter

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: unifi-exporter
  name: unifi-exporter
  namespace: klippy
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: unifi-exporter
  namespaceSelector:
    matchNames:
    - klippy
  endpoints:
  - interval: 60s
    port: http-metrics
    path: "/unifi"
    targetPort: 9130
