resources:
  - crd/flux-helm-release-crd.yaml
  - helmreleases/metallb.yaml
  - helmreleases/metrics-server.yaml
  - namespaces/klippy.yaml
  - namespaces/operators.yaml
  - workloads/helm-operator.yaml
