---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: unifi-backup
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  hostPath:
    path: /mnt/bulk_storage/unifi-backup
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-backup
  namespace: unifi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: unifi-backup
